language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_TARGET=android-22
  - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.3
  - android-23
  - extra-android-m2repository
  - "$ANDROID_TARGET"
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
script:
- "./gradlew build jacocoTestReport assembleAndroidTest"
- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
- "./gradlew connectedCheck"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- openssl aes-256-cbc -K $encrypted_1c1582332dfc_key -iv $encrypted_1c1582332dfc_iv
  -in mkeys.jks.enc -out mkeys.jks -d
